namespace OwLib
{
    using System;
    using System.Collections.Generic;

    public class MongoDBConstant
    {
        private const string AluminumExtractDataCommond = "$-alum\r\n$indicate(name={0}|userid={1})";
        private const string AluminumTreeCommond = "$-alum\r\n$indicatetree(name={0}|columns={1})";
        private const string AsphaltTreeCommond = "$-asphalt\r\n$indicatetree(name={0}|columns={1})";
        private const string BeltandRoadExtractDataCommond = "$-edb\r\n$indicate(name={0}|userid={1})";
        private const string BondExtractDataCommond = "$-bond\r\n$indicate(name={0}|userid={1})";
        private const string CanolaExtractDataCommond = "$-canola\r\n$indicate(name={0}|userid={1})\r\n";
        private const string CanolaTreeCommond = "$-canola\r\n$indicatetree(name={0}|columns={1})\r\n";
        private const string ChemicalTreeCommond = "$-thermalchemical\r\n$indicatetree(name={0}|columns={1})";
        public const string China = "0001";
        public const string ChinaTreeSourceName = "EDB_MACRO_INDICATOR_TEST";
        public const string ChinaValueSourceName = "EDB_MACRO_INDICATOR_VALUE";
        private const string CopperExtractDataCommond = "$-copper\r\n$indicate(name={0}|userid={1})";
        private const string CopperTreeCommond = "$-edb\r\nindicatetree(name={0}|columns={1}|treetype=1)";
        public const string DAT_OBSERVEDATE = "DAT_OBSERVEDATE";
        public const string DATASOURCE = "STR_DATASOURCE";
        public const string Date = "Date";
        public const string DESCRIPTION = "STR_DESCRIPTION";
        public static readonly Dictionary<MacroDataType, string> DicCommand = null;
        public static readonly Dictionary<MacroDataType, bool> DicExpand2Sec = null;
        public static readonly Dictionary<MacroDataType, string> DictMoudleTempleteName = null;
        public static readonly Dictionary<MacroDataType, string> DicTreeSource = null;
        public static readonly Dictionary<MacroDataType, int> DictSearchIndex = null;
        public static readonly Dictionary<MacroDataType, string[]> DictSearchRange = null;
        public static readonly Dictionary<MacroDataType, string> DictSearchType = null;
        public static readonly Dictionary<MacroDataType, bool> DictShowChoiceTemplate = null;
        public static readonly Dictionary<MacroDataType, bool> DictShowMyIndicators = null;
        public static readonly Dictionary<MacroDataType, string> DictTreeCmd = null;
        public static readonly Dictionary<MacroDataType, string> DicValueSource = null;
        public const string EDB_Aluminum_INDICATOR = "EDB_IC_ALUMINUM_TEST";
        public const string EDB_Asphalt_INDICATOR = "EDB_IC_ASPHALT_TEST";
        private const string EDB_CANOLA_INDICATOR = "EDB_AGRO_CANOLA_TEST";
        public const string EDB_CHEMICAL_INDICATOR = "EDB_THERMAL_CHEMICAL_TEST";
        public const string EDB_COPPER_INDICATOR = "EDB_IC_COPPER_TEST";
        public const string EDB_ESTATE_INDICATOR = "EDB_INDUSTRY_ESTATE_TEST";
        public const string EDB_FUTURE_INDICATOR = "EDB_FUTURE_INDICATOR_TEST";
        public const string EDB_FutureNew_INDICATOR = "EDB_FUTURE_INDICATOR_TEST_NEW";
        private const string EDB_GOLDMETAL_INDICATOR = "EDB_IC_GOLD_TEST";
        public const string EDB_IT_INDICATOR = "EDB_INDUSTRY_IT_TEST";
        private const string EDB_MACRO_ALL = "EDB_ALL_INDICATOR_TEST";
        public const string EDB_NonferrousMetals_INDICATOR = "EDB_INDUSTRY_NONFER_TEST";
        public const string EDB_OIL_INDICATOR = "EDB_THERMAL_OIL_TEST";
        public const string EDB_RUBBER_INDICATOR = "EDB_THERMAL_RUBBER_TEST";
        public const string EDB_SOYBEAN_INDICATOR = "EDB_SOYBEAN_TEST";
        public const string EDB_SteamCoal_INDICATOR = "EDB_THERMAL_COAL_TEST";
        public const string EDB_STEEL_INDICATOR = "EDB_STEEL_TEST";
        private const string EDB_WORLDBANK_INDICATOR = "EDB_WBGEN_INDICATOR_TEST";
        private const string EDBBeltandRoadTreeCommond = "$-edb\r\nindicatetree(name={0}|treetype=3|columns={1})";
        private const string EDBExtractDataCommond = "$-edb\r\n$indicate(name={0}|userid={1})";
        private static readonly string[] EDBSearchRanges = new string[] { "中国宏观数据库", "行业经济数据库", "全球宏观数据库", "全部数据" };
        private static readonly string[] EDBSearchRangesExp = new string[] { "中国宏观数据库", "行业经济数据库", "全球宏观数据库", "全部数据", "中国宏观数据库+行业经济数据库", "中国宏观数据库+全球宏观数据库", "全球宏观数据库+行业经济数据库" };
        private const string EDBTreeCommond = "$-edb\r\nindicatetree(name={0}|columns={1})";
        public static readonly string[] EDBTreeFields = new string[] { "STR_MACROCODE", "STR_PARENTCODE", "STR_MACRONAME", "STR_DATASOURCE", "STR_ENDDATE", "STR_MACROID", "STR_REGION", "STR_STARTDATE", "STR_UNIT", "STR_UPDATEFREQUENCY", "STR_FLAG", "STR_DESCRIPTION", "STR_ISDESCRIPTION", "STR_GXDATE", "STR_JINGDU" };
        public const string ENDDATE = "STR_ENDDATE";
        private const string EstateTreeCommond = "$-edb\r\nindicatetree(name={0}|columns={1}|treetype=2)";
        internal const string ExcelExtratCommamd = "$-edb\r\n$indicateupdate(name={0})\r\n";
        public const string ExcludeKey = "excludeKey=";
        public const string FLAG = "STR_FLAG";
        private const string FutureExtractDataCommond = "$-future\r\n$indicate(name={0}|userid={1})";
        private const string FutureNewExtractDataCommond = "$-futurenew\r\n$indicate(name={0}|userid={1})";
        private const string FutureNewTreeCommond = "$-futurenew\r\n$indicatetree(name={0}|columns={1})";
        private const string FutureTreeCommond = "$-future\r\nindicatetree(name={0}|columns={1})";
        public const string Global = "0003";
        public const string GlobalTreeSourceName = "EDB_GLOBAL_INDICATOR_TEST";
        public const string GlobalValueSourceName = "EDB_GLOBAL_INDICATOR_VALUE";
        private const string GoldMetalExtractDataCommond = "$-goldmetal\r\n$indicate(name={0}|userid={1})\r\n";
        private const string GoldMetalTreeCommond = "$-goldmetal\r\n$indicatetree(name={0}|columns={1})\r\n";
        internal const string IndicatorsCommond = "$-edb\r\n$indicatedetaile(name={0}|columns={1}|treetype=1)";
        internal const string IndicatorsCommondNew = "$-edb\r\n$indicatedetaile2(name={0}|CODES={1}|columns={2})";
        public const string Industry = "0002";
        public const string IndustryTreeSourceName = "EDB_INDUSTRY_INDICATOR_TEST";
        public const string IndustryValueSourceName = "EDB_INDUSTRY_INDICATOR_VALUE";
        internal static bool IsActive;
        public const string ISDESCRIPTION = "STR_ISDESCRIPTION";
        public const string isPCode = "isPCode=";
        public const string ISSTOP = "STR_ISSTOP";
        private const string ITTreeCommond = "$-it\r\n$indicatetree(name={0}|columns={1})";
        public const string JINGDU = "STR_JINGDU";
        private const string MAC_GYCZ = "MAC_GYCZ";
        public const string MACROCODE = "STR_MACROCODE";
        public const string MACROID = "STR_MACROID";
        public const string MACRONAME = "STR_MACRONAME";
        private const string Moudle_Name_Aluminum = "铝产业链数据库";
        private const string Moudle_Name_Asphalt = "沥青产业链数据库";
        private const string Moudle_Name_BeltandRoad = "一带一路数据库";
        private const string Moudle_Name_Canola = "菜籽油产业链数据库";
        private const string Moudle_Name_Chemical = "化工产业链数据库";
        private const string Moudle_Name_China = "中国宏观数据库";
        private const string Moudle_Name_China_Global_Industry = "经济数据库";
        private const string Moudle_Name_ChinaGlobal = "中国宏观数据库+全球宏观数据库";
        private const string Moudle_Name_ChinaIndustry = "中国宏观数据库+行业经济数据库";
        private const string Moudle_Name_Copper = "铜产业链数据库";
        private const string Moudle_Name_Estate = "房地产经济数据库";
        private const string Moudle_Name_Future = "大宗商品数据库";
        private const string Moudle_Name_FutureNew = "大宗商品数据库";
        private const string Moudle_Name_Global = "全球宏观数据库";
        private const string Moudle_Name_GlobalIndustry = "全球宏观数据库+行业经济数据库";
        private const string Moudle_Name_GoldMetal = "贵金属产业链数据库";
        private const string Moudle_Name_Industry = "行业经济数据库";
        private const string Moudle_Name_IT = "信息技术行业链数据库";
        private const string Moudle_Name_NonferrousMetals = "有色金属经济数据库";
        private const string Moudle_Name_Oil = "石油产业链数据库";
        private const string Moudle_Name_Rate = "利率走势分析";
        private const string Moudle_Name_Rubber = "天然橡胶产业链数据库";
        private const string Moudle_Name_Soybean = "大豆产业链数据库";
        private const string Moudle_Name_SteamCoal = "动力煤产业链数据库";
        private const string Moudle_Name_Steel = "钢铁产业链数据库";
        private const string Moudle_Name_WorldBank = "世界银行数据库";
        private const int MoudleCount = 0x16;
        private const string NonferrousMetalsTreeCommond = "$-nofer\r\n$indicatetree(name={0}|columns={1})";
        private const string NonferrousMetalsxtractDataCommond = "$-nofer\r\n$indicate(name={0}|userid={1})";
        public const string NUMERICALVALUE = "DEC_NUMERICALVALUE";
        private const string OilTreeCommond = "$-oilthermal\r\n$indicatetree(name={0}|columns={1})";
        public const string OLDMACROID = "STR_OldMacroID";
        public const string ORDERNUM = "DEC_ORDERNUM";
        public const string PARENTCODE = "STR_PARENTCODE";
        internal const string RateCustomTreeCommond = @"$-bond\r\n$BONDINDICATEDETAILE(userid={0}|name={1})";
        internal const string RateTreeCommond = "$-bond\r\nindicatetree(name={0}|columns={1})";
        public static readonly string[] RateTreeFields = new string[] { "STR_MACROCODE", "STR_PARENTCODE", "STR_MACRONAME", "STR_DATASOURCE", "STR_ENDDATE", "STR_MACROID", "STR_REGION", "STR_STARTDATE", "STR_UNIT", "STR_UPDATEFREQUENCY", "STR_FLAG", "STR_GXDATE" };
        public const string RateTreeSourceName = "YIEL_STANDARDYC_TREE";
        public const string RateValueSourceName = "YIEL_STANDARDYC_VALUE";
        public const string REGION = "STR_REGION";
        private const string RubberTreeCommond = "$-thermalrubber\r\n$indicatetree(name={0}|columns={1})";
        public const string SearchKey = "searchKey=";
        public const string SearchType = "searchType=";
        private const string SearchType_ALL = "008001001,008001003,008001002";
        private const string SearchType_ALL_New = "008001001,008001003,008001002";
        private const string SearchType_Aluminum = "003001004";
        private const string SearchType_Asphalt = "003001007";
        private const string SearchType_BeltandRoad = "0020";
        private const string SearchType_BeltandRoad1 = "0020";
        private const string SearchType_Canola = "008001011";
        private const string SearchType_Chemical = "008001007";
        private const string SearchType_China = "008001001";
        private const string SearchType_Copper = "003001003";
        private const string SearchType_Estate = "008001004";
        private const string SearchType_Future = "003001002";
        private const string SearchType_FutureNew = "003001002";
        private const string SearchType_Global = "008001002";
        private const string SearchType_GoldMetal = "008001009";
        private const string SearchType_Industry = "008001003";
        private const string SearchType_IT = "008001006";
        private const string SearchType_NonferrousMetals = "008001005";
        private const string SearchType_Oil = "003001005";
        private const string SearchType_Rate = "002001004";
        private const string SearchType_Rubber = "003001006";
        private const string SearchType_Soybean = "008001010";
        private const string SearchType_SteamCoal = "003001008";
        private const string SearchType_Steel = "008001008";
        private const string SearchType_WorldBank = "008001012";
        public const string Source = "source=";
        public const string SOURCEUPDATEFREQUENCY = "updateFreq";
        private const string SoybeanTreeCommond = "$-soybean\r\n$indicatetree(name={0}|columns={1})";
        public const string STARTDATE = "STR_STARTDATE";
        private const string SteamCoalTreeCommond = "$-thermal\r\n$indicatetree(name={0}|columns={1})";
        private const string SteelExtractDataCommond = "$-steel\r\n$indicate(name={0}|userid={1})\r\n";
        private const string SteelTreeCommond = "$-steel\r\n$indicatetree(name={0}|columns={1})\r\n";
        public static readonly Dictionary<MacroDataType, string[]> TreeColumnFileds = null;
        public const string UNIT = "STR_UNIT";
        public const string UPDATEFREQUENCY = "STR_UPDATEFREQUENCY";
        public const string UPDATETIME = "STR_GXDATE";
        public const string Value = "Value";
        public static readonly string[] ValueFields = new string[] { "STR_MACROID", "DAT_OBSERVEDATE", "DEC_NUMERICALVALUE" };
        private const string WorldBankExtractDataCommond = "$-wordblank\r\n$indicate(name={0}|userid={1})\r\n";
        private const string WorldBankTreeCommond = "$-wordblank\r\n$indicatetree(name={0}|columns={1})\r\n";
        public const string YUANMING = "STR_YUANMING";

        static MongoDBConstant()
        {
            DicTreeSource = new Dictionary<MacroDataType, string>(0x16);
            DicTreeSource[MacroDataType.China] = "EDB_MACRO_INDICATOR_TEST";
            DicTreeSource[MacroDataType.Industry] = "EDB_INDUSTRY_INDICATOR_TEST";
            DicTreeSource[MacroDataType.Global] = "EDB_GLOBAL_INDICATOR_TEST";
            DicTreeSource[MacroDataType.Rate] = "YIEL_STANDARDYC_TREE";
            DicTreeSource[MacroDataType.Future] = "EDB_FUTURE_INDICATOR_TEST";
            DicTreeSource[MacroDataType.Estate] = "EDB_INDUSTRY_ESTATE_TEST";
            DicTreeSource[MacroDataType.Copper] = "EDB_IC_COPPER_TEST";
            DicTreeSource[MacroDataType.FutureNew] = "EDB_FUTURE_INDICATOR_TEST_NEW";
            DicTreeSource[MacroDataType.Aluminum] = "EDB_IC_ALUMINUM_TEST";
            DicTreeSource[MacroDataType.NonferrousMetals] = "EDB_INDUSTRY_NONFER_TEST";
            DicTreeSource[MacroDataType.Asphalt] = "EDB_IC_ASPHALT_TEST";
            DicTreeSource[MacroDataType.SteamCoal] = "EDB_THERMAL_COAL_TEST";
            DicTreeSource[MacroDataType.IT] = "EDB_INDUSTRY_IT_TEST";
            DicTreeSource[MacroDataType.Rubber] = "EDB_THERMAL_RUBBER_TEST";
            DicTreeSource[MacroDataType.Oil] = "EDB_THERMAL_OIL_TEST";
            DicTreeSource[MacroDataType.Chemical] = "EDB_THERMAL_CHEMICAL_TEST";
            DicTreeSource[MacroDataType.Soybean] = "EDB_SOYBEAN_TEST";
            DicTreeSource[MacroDataType.Steel] = "EDB_STEEL_TEST";
            DicTreeSource[MacroDataType.WorldBank] = "EDB_WBGEN_INDICATOR_TEST";
            DicTreeSource[MacroDataType.GoldMetal] = "EDB_IC_GOLD_TEST";
            DicTreeSource[MacroDataType.Canola] = "EDB_AGRO_CANOLA_TEST";
            DicTreeSource[MacroDataType.All] = "EDB_ALL_INDICATOR_TEST";
            DicTreeSource[MacroDataType.BeltandRoad] = "MAC_GYCZ";
            DicValueSource = new Dictionary<MacroDataType, string>(0x16);
            DicValueSource[MacroDataType.China] = "EDB_MACRO_INDICATOR_VALUE";
            DicValueSource[MacroDataType.Industry] = "EDB_INDUSTRY_INDICATOR_VALUE";
            DicValueSource[MacroDataType.Global] = "EDB_GLOBAL_INDICATOR_VALUE";
            DicValueSource[MacroDataType.Rate] = "YIEL_STANDARDYC_VALUE";
            DicValueSource[MacroDataType.Future] = "EDB_INDUSTRY_INDICATOR_VALUE";
            DicValueSource[MacroDataType.Estate] = "UNDEFINED";
            DicValueSource[MacroDataType.Copper] = "UNDEFINED";
            DicValueSource[MacroDataType.FutureNew] = "EDB_INDUSTRY_INDICATOR_VALUE";
            DicValueSource[MacroDataType.Aluminum] = "UNDEFINED";
            DicValueSource[MacroDataType.NonferrousMetals] = "UNDEFINED";
            DicValueSource[MacroDataType.Asphalt] = "UNDEFINED";
            DicValueSource[MacroDataType.SteamCoal] = "UNDEFINED";
            DicValueSource[MacroDataType.IT] = "UNDEFINED";
            DicValueSource[MacroDataType.Rubber] = "UNDEFINED";
            DicValueSource[MacroDataType.Oil] = "UNDEFINED";
            DicValueSource[MacroDataType.Chemical] = "UNDEFINED";
            DicValueSource[MacroDataType.Soybean] = "UNDEFINED";
            DicValueSource[MacroDataType.Steel] = "UNDEFINED";
            DicValueSource[MacroDataType.WorldBank] = "UNDEFINED";
            DicValueSource[MacroDataType.GoldMetal] = "UNDEFINED";
            DicValueSource[MacroDataType.Canola] = "UNDEFINED";
            DicCommand = new Dictionary<MacroDataType, string>(0x16);
            DicCommand[MacroDataType.China] = "$-edb\r\n$indicate(name={0}|userid={1})";
            DicCommand[MacroDataType.Global] = "$-edb\r\n$indicate(name={0}|userid={1})";
            DicCommand[MacroDataType.Industry] = "$-edb\r\n$indicate(name={0}|userid={1})";
            DicCommand[MacroDataType.Future] = "$-future\r\n$indicate(name={0}|userid={1})";
            DicCommand[MacroDataType.Rate] = "$-bond\r\n$indicate(name={0}|userid={1})";
            DicCommand[MacroDataType.Estate] = "$-edb\r\n$indicate(name={0}|userid={1})";
            DicCommand[MacroDataType.Copper] = "$-edb\r\n$indicate(name={0}|userid={1})";
            DicCommand[MacroDataType.FutureNew] = "$-futurenew\r\n$indicate(name={0}|userid={1})";
            DicCommand[MacroDataType.NonferrousMetals] = "$-nofer\r\n$indicate(name={0}|userid={1})";
            DicCommand[MacroDataType.Aluminum] = "$-alum\r\n$indicate(name={0}|userid={1})";
            DicCommand[MacroDataType.Asphalt] = "$-edb\r\n$indicate(name={0}|userid={1})";
            DicCommand[MacroDataType.SteamCoal] = "$-edb\r\n$indicate(name={0}|userid={1})";
            DicCommand[MacroDataType.IT] = "$-edb\r\n$indicate(name={0}|userid={1})";
            DicCommand[MacroDataType.Rubber] = "$-edb\r\n$indicate(name={0}|userid={1})";
            DicCommand[MacroDataType.Oil] = "$-edb\r\n$indicate(name={0}|userid={1})";
            DicCommand[MacroDataType.Chemical] = "$-edb\r\n$indicate(name={0}|userid={1})";
            DicCommand[MacroDataType.Soybean] = "$-edb\r\n$indicate(name={0}|userid={1})";
            DicCommand[MacroDataType.Steel] = "$-steel\r\n$indicate(name={0}|userid={1})\r\n";
            DicCommand[MacroDataType.WorldBank] = "$-wordblank\r\n$indicate(name={0}|userid={1})\r\n";
            DicCommand[MacroDataType.GoldMetal] = "$-goldmetal\r\n$indicate(name={0}|userid={1})\r\n";
            DicCommand[MacroDataType.Canola] = "$-canola\r\n$indicate(name={0}|userid={1})\r\n";
            DicCommand[MacroDataType.BeltandRoad] = "$-edb\r\n$indicate(name={0}|userid={1})";
            DictTreeCmd = new Dictionary<MacroDataType, string>(0x16);
            DictTreeCmd[MacroDataType.China] = "$-edb\r\nindicatetree(name={0}|columns={1})";
            DictTreeCmd[MacroDataType.Global] = "$-edb\r\nindicatetree(name={0}|columns={1})";
            DictTreeCmd[MacroDataType.Industry] = "$-edb\r\nindicatetree(name={0}|columns={1})";
            DictTreeCmd[MacroDataType.Future] = "$-future\r\nindicatetree(name={0}|columns={1})";
            DictTreeCmd[MacroDataType.Rate] = "$-bond\r\nindicatetree(name={0}|columns={1})";
            DictTreeCmd[MacroDataType.Estate] = "$-edb\r\nindicatetree(name={0}|columns={1}|treetype=2)";
            DictTreeCmd[MacroDataType.Copper] = "$-edb\r\nindicatetree(name={0}|columns={1}|treetype=1)";
            DictTreeCmd[MacroDataType.FutureNew] = "$-futurenew\r\n$indicatetree(name={0}|columns={1})";
            DictTreeCmd[MacroDataType.NonferrousMetals] = "$-nofer\r\n$indicatetree(name={0}|columns={1})";
            DictTreeCmd[MacroDataType.Aluminum] = "$-alum\r\n$indicatetree(name={0}|columns={1})";
            DictTreeCmd[MacroDataType.Asphalt] = "$-asphalt\r\n$indicatetree(name={0}|columns={1})";
            DictTreeCmd[MacroDataType.SteamCoal] = "$-thermal\r\n$indicatetree(name={0}|columns={1})";
            DictTreeCmd[MacroDataType.IT] = "$-it\r\n$indicatetree(name={0}|columns={1})";
            DictTreeCmd[MacroDataType.Rubber] = "$-thermalrubber\r\n$indicatetree(name={0}|columns={1})";
            DictTreeCmd[MacroDataType.Oil] = "$-oilthermal\r\n$indicatetree(name={0}|columns={1})";
            DictTreeCmd[MacroDataType.Chemical] = "$-thermalchemical\r\n$indicatetree(name={0}|columns={1})";
            DictTreeCmd[MacroDataType.Soybean] = "$-soybean\r\n$indicatetree(name={0}|columns={1})";
            DictTreeCmd[MacroDataType.Steel] = "$-steel\r\n$indicatetree(name={0}|columns={1})\r\n";
            DictTreeCmd[MacroDataType.WorldBank] = "$-wordblank\r\n$indicatetree(name={0}|columns={1})\r\n";
            DictTreeCmd[MacroDataType.GoldMetal] = "$-goldmetal\r\n$indicatetree(name={0}|columns={1})\r\n";
            DictTreeCmd[MacroDataType.Canola] = "$-canola\r\n$indicatetree(name={0}|columns={1})\r\n";
            DictTreeCmd[MacroDataType.BeltandRoad] = "$-edb\r\nindicatetree(name={0}|treetype=3|columns={1})";
            TreeColumnFileds = new Dictionary<MacroDataType, string[]>(0x16);
            TreeColumnFileds[MacroDataType.China] = EDBTreeFields;
            TreeColumnFileds[MacroDataType.Global] = EDBTreeFields;
            TreeColumnFileds[MacroDataType.Industry] = EDBTreeFields;
            TreeColumnFileds[MacroDataType.Future] = EDBTreeFields;
            TreeColumnFileds[MacroDataType.Rate] = RateTreeFields;
            TreeColumnFileds[MacroDataType.Estate] = EDBTreeFields;
            TreeColumnFileds[MacroDataType.Copper] = EDBTreeFields;
            TreeColumnFileds[MacroDataType.FutureNew] = EDBTreeFields;
            TreeColumnFileds[MacroDataType.NonferrousMetals] = EDBTreeFields;
            TreeColumnFileds[MacroDataType.Aluminum] = EDBTreeFields;
            TreeColumnFileds[MacroDataType.Asphalt] = EDBTreeFields;
            TreeColumnFileds[MacroDataType.SteamCoal] = EDBTreeFields;
            TreeColumnFileds[MacroDataType.IT] = EDBTreeFields;
            TreeColumnFileds[MacroDataType.Rubber] = EDBTreeFields;
            TreeColumnFileds[MacroDataType.Oil] = EDBTreeFields;
            TreeColumnFileds[MacroDataType.Chemical] = EDBTreeFields;
            TreeColumnFileds[MacroDataType.Soybean] = EDBTreeFields;
            TreeColumnFileds[MacroDataType.Steel] = EDBTreeFields;
            TreeColumnFileds[MacroDataType.WorldBank] = EDBTreeFields;
            TreeColumnFileds[MacroDataType.GoldMetal] = EDBTreeFields;
            TreeColumnFileds[MacroDataType.Canola] = EDBTreeFields;
            TreeColumnFileds[MacroDataType.BeltandRoad] = EDBTreeFields;
            DictShowChoiceTemplate = new Dictionary<MacroDataType, bool>(0x16);
            DictShowChoiceTemplate[MacroDataType.China] = true;
            DictShowChoiceTemplate[MacroDataType.Global] = false;
            DictShowChoiceTemplate[MacroDataType.Industry] = true;
            DictShowChoiceTemplate[MacroDataType.Future] = true;
            DictShowChoiceTemplate[MacroDataType.Rate] = true;
            DictShowChoiceTemplate[MacroDataType.Estate] = false;
            DictShowChoiceTemplate[MacroDataType.Copper] = false;
            DictShowChoiceTemplate[MacroDataType.Future] = false;
            DictShowChoiceTemplate[MacroDataType.FutureNew] = false;
            DictShowChoiceTemplate[MacroDataType.NonferrousMetals] = false;
            DictShowChoiceTemplate[MacroDataType.Aluminum] = false;
            DictShowChoiceTemplate[MacroDataType.Asphalt] = false;
            DictShowChoiceTemplate[MacroDataType.SteamCoal] = false;
            DictShowChoiceTemplate[MacroDataType.IT] = false;
            DictShowChoiceTemplate[MacroDataType.Rubber] = false;
            DictShowChoiceTemplate[MacroDataType.Oil] = false;
            DictShowChoiceTemplate[MacroDataType.Chemical] = false;
            DictShowChoiceTemplate[MacroDataType.Soybean] = false;
            DictShowChoiceTemplate[MacroDataType.Steel] = false;
            DictShowChoiceTemplate[MacroDataType.WorldBank] = false;
            DictShowChoiceTemplate[MacroDataType.GoldMetal] = false;
            DictShowChoiceTemplate[MacroDataType.Canola] = false;
            DictShowChoiceTemplate[MacroDataType.BeltandRoad] = false;
            DictShowMyIndicators = new Dictionary<MacroDataType, bool>(0x16);
            DictShowMyIndicators[MacroDataType.China] = true;
            DictShowMyIndicators[MacroDataType.Global] = true;
            DictShowMyIndicators[MacroDataType.Industry] = true;
            DictShowMyIndicators[MacroDataType.Future] = false;
            DictShowMyIndicators[MacroDataType.Rate] = false;
            DictShowMyIndicators[MacroDataType.Estate] = false;
            DictShowMyIndicators[MacroDataType.Copper] = false;
            DictShowMyIndicators[MacroDataType.Future] = false;
            DictShowMyIndicators[MacroDataType.FutureNew] = false;
            DictShowMyIndicators[MacroDataType.NonferrousMetals] = false;
            DictShowMyIndicators[MacroDataType.Aluminum] = false;
            DictShowMyIndicators[MacroDataType.Asphalt] = false;
            DictShowMyIndicators[MacroDataType.SteamCoal] = false;
            DictShowMyIndicators[MacroDataType.IT] = false;
            DictShowMyIndicators[MacroDataType.Rubber] = false;
            DictShowMyIndicators[MacroDataType.Oil] = false;
            DictShowMyIndicators[MacroDataType.Chemical] = false;
            DictShowMyIndicators[MacroDataType.Soybean] = false;
            DictShowMyIndicators[MacroDataType.Steel] = false;
            DictShowMyIndicators[MacroDataType.WorldBank] = false;
            DictShowMyIndicators[MacroDataType.GoldMetal] = false;
            DictShowMyIndicators[MacroDataType.Canola] = false;
            DictShowMyIndicators[MacroDataType.BeltandRoad] = false;
            DictSearchRange = new Dictionary<MacroDataType, string[]>(0x16);
            DictSearchRange[MacroDataType.China] = EDBSearchRangesExp;
            DictSearchRange[MacroDataType.Global] = EDBSearchRangesExp;
            DictSearchRange[MacroDataType.Industry] = EDBSearchRangesExp;
            DictSearchRange[MacroDataType.Future] = new string[] { "大宗商品数据库" };
            DictSearchRange[MacroDataType.Rate] = new string[] { "利率走势分析" };
            DictSearchRange[MacroDataType.Estate] = new string[] { "房地产经济数据库" };
            DictSearchRange[MacroDataType.Copper] = new string[] { "铜产业链数据库" };
            DictSearchRange[MacroDataType.Future] = new string[] { "大宗商品数据库" };
            DictSearchRange[MacroDataType.FutureNew] = new string[] { "大宗商品数据库" };
            DictSearchRange[MacroDataType.NonferrousMetals] = new string[] { "有色金属经济数据库" };
            DictSearchRange[MacroDataType.Aluminum] = new string[] { "铝产业链数据库" };
            DictSearchRange[MacroDataType.Asphalt] = new string[] { "沥青产业链数据库" };
            DictSearchRange[MacroDataType.SteamCoal] = new string[] { "动力煤产业链数据库" };
            DictSearchRange[MacroDataType.IT] = new string[] { "信息技术行业链数据库" };
            DictSearchRange[MacroDataType.Rubber] = new string[] { "天然橡胶产业链数据库" };
            DictSearchRange[MacroDataType.Oil] = new string[] { "石油产业链数据库" };
            DictSearchRange[MacroDataType.Chemical] = new string[] { "化工产业链数据库" };
            DictSearchRange[MacroDataType.Soybean] = new string[] { "大豆产业链数据库" };
            DictSearchRange[MacroDataType.Steel] = new string[] { "钢铁产业链数据库" };
            DictSearchRange[MacroDataType.WorldBank] = new string[] { "世界银行数据库" };
            DictSearchRange[MacroDataType.GoldMetal] = new string[] { "贵金属产业链数据库" };
            DictSearchRange[MacroDataType.Canola] = new string[] { "菜籽油产业链数据库" };
            DictSearchRange[MacroDataType.BeltandRoad] = new string[] { "一带一路数据库" };
            DictSearchIndex = new Dictionary<MacroDataType, int>(0x16);
            DictSearchIndex[MacroDataType.China] = 3;
            DictSearchIndex[MacroDataType.Global] = 3;
            DictSearchIndex[MacroDataType.Industry] = 3;
            DictSearchIndex[MacroDataType.All] = 3;
            DictSearchIndex[MacroDataType.Future] = 0;
            DictSearchIndex[MacroDataType.Rate] = 0;
            DictSearchIndex[MacroDataType.Estate] = 0;
            DictSearchIndex[MacroDataType.Copper] = 0;
            DictSearchIndex[MacroDataType.NonferrousMetals] = 0;
            DictSearchIndex[MacroDataType.Aluminum] = 0;
            DictSearchIndex[MacroDataType.FutureNew] = 0;
            DictSearchIndex[MacroDataType.Asphalt] = 0;
            DictSearchIndex[MacroDataType.SteamCoal] = 0;
            DictSearchIndex[MacroDataType.IT] = 0;
            DictSearchIndex[MacroDataType.Rubber] = 0;
            DictSearchIndex[MacroDataType.Oil] = 0;
            DictSearchIndex[MacroDataType.Chemical] = 0;
            DictSearchIndex[MacroDataType.Soybean] = 0;
            DictSearchIndex[MacroDataType.Steel] = 0;
            DictSearchIndex[MacroDataType.WorldBank] = 0;
            DictSearchIndex[MacroDataType.GoldMetal] = 0;
            DictSearchIndex[MacroDataType.Canola] = 0;
            DictSearchIndex[MacroDataType.BeltandRoad] = 0;
            DicExpand2Sec = new Dictionary<MacroDataType, bool>(0x16);
            DicExpand2Sec[MacroDataType.China] = false;
            DicExpand2Sec[MacroDataType.Global] = false;
            DicExpand2Sec[MacroDataType.Industry] = false;
            DicExpand2Sec[MacroDataType.Future] = true;
            DicExpand2Sec[MacroDataType.Rate] = true;
            DicExpand2Sec[MacroDataType.Estate] = true;
            DicExpand2Sec[MacroDataType.Copper] = true;
            DicExpand2Sec[MacroDataType.FutureNew] = false;
            DicExpand2Sec[MacroDataType.Aluminum] = true;
            DicExpand2Sec[MacroDataType.NonferrousMetals] = true;
            DicExpand2Sec[MacroDataType.Asphalt] = true;
            DicExpand2Sec[MacroDataType.SteamCoal] = true;
            DicExpand2Sec[MacroDataType.IT] = true;
            DicExpand2Sec[MacroDataType.Rubber] = true;
            DicExpand2Sec[MacroDataType.Oil] = true;
            DicExpand2Sec[MacroDataType.Chemical] = true;
            DicExpand2Sec[MacroDataType.Soybean] = true;
            DicExpand2Sec[MacroDataType.Steel] = true;
            DicExpand2Sec[MacroDataType.WorldBank] = false;
            DicExpand2Sec[MacroDataType.GoldMetal] = true;
            DicExpand2Sec[MacroDataType.Canola] = true;
            DicExpand2Sec[MacroDataType.BeltandRoad] = true;
            DictMoudleTempleteName = new Dictionary<MacroDataType, string>(0x16);
            DictMoudleTempleteName[MacroDataType.China] = "中国宏观数据库";
            DictMoudleTempleteName[MacroDataType.Global] = "全球宏观数据库";
            DictMoudleTempleteName[MacroDataType.Industry] = "行业经济数据库";
            DictMoudleTempleteName[MacroDataType.Future] = "大宗商品数据库";
            DictMoudleTempleteName[MacroDataType.Rate] = "利率走势分析";
            DictMoudleTempleteName[MacroDataType.Estate] = "房地产经济数据库";
            DictMoudleTempleteName[MacroDataType.Copper] = "铜产业链数据库";
            DictMoudleTempleteName[MacroDataType.FutureNew] = "大宗商品数据库";
            DictMoudleTempleteName[MacroDataType.Aluminum] = "铝产业链数据库";
            DictMoudleTempleteName[MacroDataType.NonferrousMetals] = "有色金属经济数据库";
            DictMoudleTempleteName[MacroDataType.Asphalt] = "沥青产业链数据库";
            DictMoudleTempleteName[MacroDataType.SteamCoal] = "动力煤产业链数据库";
            DictMoudleTempleteName[MacroDataType.IT] = "信息技术行业链数据库";
            DictMoudleTempleteName[MacroDataType.Rubber] = "天然橡胶产业链数据库";
            DictMoudleTempleteName[MacroDataType.Oil] = "石油产业链数据库";
            DictMoudleTempleteName[MacroDataType.Chemical] = "化工产业链数据库";
            DictMoudleTempleteName[MacroDataType.Soybean] = "大豆产业链数据库";
            DictMoudleTempleteName[MacroDataType.Steel] = "钢铁产业链数据库";
            DictMoudleTempleteName[MacroDataType.WorldBank] = "世界银行数据库";
            DictMoudleTempleteName[MacroDataType.GoldMetal] = "贵金属产业链数据库";
            DictMoudleTempleteName[MacroDataType.Canola] = "菜籽油产业链数据库";
            DictMoudleTempleteName[MacroDataType.BeltandRoad] = "一带一路数据库";
            DictSearchType = new Dictionary<MacroDataType, string>(0x16);
            DictSearchType[MacroDataType.China] = "008001001";
            DictSearchType[MacroDataType.Global] = "008001002";
            DictSearchType[MacroDataType.Industry] = "008001003";
            DictSearchType[MacroDataType.All] = "008001001,008001003,008001002";
            DictSearchType[MacroDataType.Future] = "003001002";
            DictSearchType[MacroDataType.Rate] = "002001004";
            DictSearchType[MacroDataType.Estate] = "008001004";
            DictSearchType[MacroDataType.Copper] = "003001003";
            DictSearchType[MacroDataType.FutureNew] = "003001002";
            DictSearchType[MacroDataType.Aluminum] = "003001004";
            DictSearchType[MacroDataType.NonferrousMetals] = "008001005";
            DictSearchType[MacroDataType.Asphalt] = "003001007";
            DictSearchType[MacroDataType.SteamCoal] = "003001008";
            DictSearchType[MacroDataType.IT] = "008001006";
            DictSearchType[MacroDataType.Rubber] = "003001006";
            DictSearchType[MacroDataType.Oil] = "003001005";
            DictSearchType[MacroDataType.Chemical] = "008001007";
            DictSearchType[MacroDataType.Soybean] = "008001010";
            DictSearchType[MacroDataType.Steel] = "008001008";
            DictSearchType[MacroDataType.WorldBank] = "008001012";
            DictSearchType[MacroDataType.GoldMetal] = "008001009";
            DictSearchType[MacroDataType.Canola] = "008001011";
            DictSearchType[MacroDataType.BeltandRoad] = "0020";
        }

        public static bool ShowFunctionExportButton(MacroDataType type)
        {
            return (MacroDataType.Rate != type);
        }
    }
}

